# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/joname1"
  #weibo: "#"
  #rss: "#"
  zhihu: "http://www.zhihu.com/people/joname-liangtan"
  #douban: "#"
  mail: "mailto:joname.liangtan@gmail.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: favicon.ico

#你的头像url
avatar: https://avatars0.githubusercontent.com/u/15252214?v=3&s=460
#是否开启分享
share_jia: false
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
#friends:
#  奥巴马的博客: http://localhost:4000/
#  卡卡的美丽传说: http://localhost:4000/
#  本泽马的博客: http://localhost:4000/
#  吉格斯的博客: http://localhost:4000/
#  习大大大不同: http://localhost:4000/
#  托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 擅长各项前端技能及翻墙技术, 深入研究移动端开发与前端性能. PS:作者乃膜蛤狂人, 有严重强迫症, 逼格崇拜症.
